openapi: 3.0.3
info:
  title: MailBaby Email Delivery API
  description: |
    **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.**


    # üìå Overview

    This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net).


    # üîê Authentication

    In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site.

    We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page.
  termsOfService: https://www.interserver.net/terms-of-service.html
  contact:
    name: Mail Baby
    url: https://www.mail.baby/contact/
    email: support@interserver.net
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
externalDocs:
  description: FAQ
  url: https://www.mail.baby/tips/
servers:
- url: https://api.mailbaby.net
  description: Live API Endpoint
- url: http://mystage.interserver.net:8787
  description: Temporary API Endpoint
- url: https://virtserver.swaggerhub.com/InterServer/Mail-Baby/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- apiKeyAuth: []
paths:
  /mail:
    get:
      summary: displays a list of mail service orders
      operationId: getMailOrders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
                x-content-type: application/json
          links:
            sendMailByIdLink:
              operationId: sendMail
              parameters:
                id: $response.body#/0/id
              description: The `id` value returned in the response can be used as
                the `id` parameter in `GET /mail/advsend`.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "404":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
  /mail/send:
    post:
      summary: Sends an Email
      description: |
        Sends an email through one of your mail orders.

        *Note*: If you want to send to multiple recipients or use file attachments use the advsend (Advanced Send) call instead.
      operationId: sendMail
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendMail'
          application/json:
            schema:
              $ref: '#/components/schemas/SendMail'
        required: true
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "400":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
  /mail/advsend:
    post:
      summary: Sends an Email with Advanced Options
      description: "Sends An email through one of your mail orders allowing additional\
        \ options such as file attachments, cc, bcc, etc."
      operationId: sendAdvMail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMailAdv'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendMailAdv'
        required: true
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        "400":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
  /mail/log:
    get:
      summary: displays the mail log
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      operationId: viewMailLog
      parameters:
      - name: id
        in: query
        description: The ID of your mail order this will be sent through.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: search
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
          default: 0
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 10000
          minimum: 1
          type: integer
          format: int32
          default: 100
      - name: startDate
        in: query
        description: earliest date to get emails in unix timestamp format
        required: false
        style: form
        explode: true
        schema:
          maximum: 9999999999
          minimum: 0
          type: integer
          format: int64
      - name: endDate
        in: query
        description: earliest date to get emails in unix timestamp format
        required: false
        style: form
        explode: true
        schema:
          maximum: 9999999999
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MailLog'
        "400":
          description: bad input parameter
  /ping:
    get:
      summary: Checks if the server is running
      operationId: pingServer
      parameters: []
      responses:
        "200":
          description: Server is up and running
        default:
          description: Something is wrong
      security: []
components:
  schemas:
    GenericResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        text:
          type: string
          example: The command completed successfully.
      example:
        text: The command completed successfully.
        status: ok
    MailLog:
      required:
      - emails
      - limit
      - skip
      - total
      type: object
      properties:
        total:
          type: integer
          description: total number of mail log entries
          example: 10234
        skip:
          type: integer
          description: number of emails skipped in listing
          example: 0
        limit:
          type: integer
          description: number of emails to return
          example: 100
        emails:
          type: array
          items:
            $ref: '#/components/schemas/MailLogEntry'
      description: Mail log records
      example:
        emails:
        - date: "Thu, 14 Oct 2021 08:50:09 -0400"
          subject: sell 0.005 shares
          origin: 199.231.189.154
          queued: 2021-10-14T12:50:15.487Z
          logger: logger
          connectionKey: 206.72.200.46:interserver.net:25
          interface: feeder
          md5Match: 1
          mxPort: 25
          sentBodySize: 63
          lockTime: 1634215818533
          from: person@mysite.com
          id: 17c7eda538e0005d03
          locked: 1
          seq: 1
          sentBodyHash: 1d7058e6a30369f200b0c34fab2fac92
          created: 2021-10-14 08:50:10
          transtype: ESMTPSA
          sourceMd5: 1d7058e6a30369f200b0c34fab2fac92
          _lock: lock 17c7eda538e0005d03 001
          messageId: <vmiLEebsuCbSpUxD7oN3REpaN4VbN6BrdCAbNKIrdAo@relay0.mailbaby.net>
          sendingZone: interserver
          mxHostname: mx.j.is.cc
          transhost: relay0.mailbaby.net
          originhost: 199.231.189.154
          domain: interserver.net
          bodySize: 63
          recipient: client@isp.com
          assigned: relay1
          _id: 103172
          to: client@isp.com
          time: 1634215809
          user: mb5658
        - date: "Thu, 14 Oct 2021 08:50:09 -0400"
          subject: sell 0.005 shares
          origin: 199.231.189.154
          queued: 2021-10-14T12:50:15.487Z
          logger: logger
          connectionKey: 206.72.200.46:interserver.net:25
          interface: feeder
          md5Match: 1
          mxPort: 25
          sentBodySize: 63
          lockTime: 1634215818533
          from: person@mysite.com
          id: 17c7eda538e0005d03
          locked: 1
          seq: 1
          sentBodyHash: 1d7058e6a30369f200b0c34fab2fac92
          created: 2021-10-14 08:50:10
          transtype: ESMTPSA
          sourceMd5: 1d7058e6a30369f200b0c34fab2fac92
          _lock: lock 17c7eda538e0005d03 001
          messageId: <vmiLEebsuCbSpUxD7oN3REpaN4VbN6BrdCAbNKIrdAo@relay0.mailbaby.net>
          sendingZone: interserver
          mxHostname: mx.j.is.cc
          transhost: relay0.mailbaby.net
          originhost: 199.231.189.154
          domain: interserver.net
          bodySize: 63
          recipient: client@isp.com
          assigned: relay1
          _id: 103172
          to: client@isp.com
          time: 1634215809
          user: mb5658
        total: 10234
        limit: 100
        skip: 0
    MailLogEntry:
      required:
      - _id
      - _lock
      - assigned
      - bodySize
      - connectionKey
      - created
      - date
      - domain
      - from
      - id
      - interface
      - lockTime
      - locked
      - logger
      - md5Match
      - messageId
      - mxHostname
      - mxPort
      - origin
      - originhost
      - queued
      - recipient
      - sendingZone
      - sentBodyHash
      - sentBodySize
      - seq
      - sourceMd5
      - subject
      - time
      - to
      - transhost
      - transtype
      - user
      type: object
      properties:
        _id:
          type: integer
          description: internal db id
          example: 103172
        id:
          type: string
          description: mail id
          example: 17c7eda538e0005d03
        from:
          type: string
          description: from address
          example: person@mysite.com
        to:
          type: string
          description: to address
          example: client@isp.com
        subject:
          type: string
          description: email subject
          example: sell 0.005 shares
        messageId:
          type: string
          description: message id
          example: <vmiLEebsuCbSpUxD7oN3REpaN4VbN6BrdCAbNKIrdAo@relay0.mailbaby.net>
        created:
          type: string
          description: creation date
          example: 2021-10-14 08:50:10
        time:
          type: integer
          description: creation timestamp
          example: 1634215809
        user:
          type: string
          description: user account
          example: mb5658
        transtype:
          type: string
          description: transaction type
          example: ESMTPSA
        transhost:
          type: string
          description: transaction host
          example: relay0.mailbaby.net
        originhost:
          type: string
          description: origin host
          example: 199.231.189.154
        origin:
          type: string
          description: origin ip
          example: 199.231.189.154
        interface:
          type: string
          description: interface name
          example: feeder
        date:
          type: string
          description: date processed
          example: "Thu, 14 Oct 2021 08:50:09 -0400"
        sendingZone:
          type: string
          description: sending zone
          example: interserver
        bodySize:
          type: integer
          description: email body size in bytes
          example: 63
        sourceMd5:
          type: string
          description: md5 sum of the email
          example: 1d7058e6a30369f200b0c34fab2fac92
        seq:
          type: integer
          description: delivery sequency
          example: 1
        domain:
          type: string
          description: to address domain
          example: interserver.net
        recipient:
          type: string
          description: email receiver address
          example: client@isp.com
        locked:
          type: integer
          description: locked status
          example: 1
        lockTime:
          type: integer
          description: lock timestamp
          example: 1634215818533
        assigned:
          type: string
          description: assigned server
          example: relay1
        queued:
          type: string
          description: queued timestamp
          example: 2021-10-14T12:50:15.487Z
        _lock:
          type: string
          description: lock id
          example: lock 17c7eda538e0005d03 001
        logger:
          type: string
          description: logger
          example: null
        mxPort:
          type: integer
          description: mx port number
          example: 25
        connectionKey:
          type: string
          description: connection key
          example: 206.72.200.46:interserver.net:25
        mxHostname:
          type: string
          description: mx hostname
          example: mx.j.is.cc
        sentBodyHash:
          type: string
          description: body hash
          example: 1d7058e6a30369f200b0c34fab2fac92
        sentBodySize:
          type: integer
          description: sent body size in bytes
          example: 63
        md5Match:
          type: integer
          description: md5 checksum matching result
          example: 1
      description: An email record
      example:
        date: "Thu, 14 Oct 2021 08:50:09 -0400"
        subject: sell 0.005 shares
        origin: 199.231.189.154
        queued: 2021-10-14T12:50:15.487Z
        logger: logger
        connectionKey: 206.72.200.46:interserver.net:25
        interface: feeder
        md5Match: 1
        mxPort: 25
        sentBodySize: 63
        lockTime: 1634215818533
        from: person@mysite.com
        id: 17c7eda538e0005d03
        locked: 1
        seq: 1
        sentBodyHash: 1d7058e6a30369f200b0c34fab2fac92
        created: 2021-10-14 08:50:10
        transtype: ESMTPSA
        sourceMd5: 1d7058e6a30369f200b0c34fab2fac92
        _lock: lock 17c7eda538e0005d03 001
        messageId: <vmiLEebsuCbSpUxD7oN3REpaN4VbN6BrdCAbNKIrdAo@relay0.mailbaby.net>
        sendingZone: interserver
        mxHostname: mx.j.is.cc
        transhost: relay0.mailbaby.net
        originhost: 199.231.189.154
        domain: interserver.net
        bodySize: 63
        recipient: client@isp.com
        assigned: relay1
        _id: 103172
        to: client@isp.com
        time: 1634215809
        user: mb5658
    SendMail:
      required:
      - body
      - from
      - subject
      - to
      type: object
      properties:
        to:
          type: string
          description: The Contact whom is the primary recipient of this email.
          example: johndoe@company.com
        from:
          type: string
          description: The contact whom is the this email is from.
          example: janedoe@company.com
        subject:
          type: string
          description: The subject or title of the email
          example: Attention Client
        body:
          type: string
          description: The main email contents.
          example: This is an email to inform you that something noteworthy happened.
      description: Details for an Email
    SendMailAdv:
      title: Email details
      required:
      - body
      - from
      - subject
      - to
      type: object
      properties:
        subject:
          type: string
          description: The subject or title of the email
          example: Your Package has been Delivered!
        body:
          type: string
          description: The main email contents.
          example: "The package you ordered on 2021-01-23 has been delivered. If the\
            \ package is broken into many pieces, please blaim someone else."
        from:
          $ref: '#/components/schemas/SendMailAdv_from'
        to:
          type: array
          description: A list of destionation email addresses to send this to
          items:
            $ref: '#/components/schemas/SendMailAdv_to'
        replyto:
          type: array
          description: (optional) A list of email addresses that specify where replies
            to the email should be sent instead of the _from_ address.
          items:
            $ref: '#/components/schemas/SendMailAdv_replyto'
        cc:
          type: array
          description: (optional) A list of email addresses to carbon copy this message
            to.  They are listed on the email and anyone getting the email can see
            this full list of Contacts who received the email as well.
          items:
            $ref: '#/components/schemas/SendMailAdv_cc'
        bcc:
          type: array
          description: (optional) list of email addresses that should receive copies
            of the email.  They are hidden on the email and anyone gettitng the email
            would not see the other people getting the email in this list.
          items:
            $ref: '#/components/schemas/SendMailAdv_bcc'
        attachments:
          type: array
          description: (optional) File attachments to include in the email.  The file
            contents must be base64 encoded!
          items:
            $ref: '#/components/schemas/SendMailAdv_attachments'
        id:
          type: integer
          description: (optional)  ID of the Mail order within our system to use as
            the Mail Account.
          format: int64
          example: 5000
      description: Details for an Email
    inline_response_200:
      required:
      - id
      - status
      - username
      type: object
      properties:
        id:
          type: integer
          example: 1234
        status:
          type: string
          example: active
        username:
          type: string
          example: mb1234
        password:
          type: string
          example: guest123
        comment:
          type: string
          example: main mail account
      example:
        password: guest123
        comment: main mail account
        id: 1234
        status: active
        username: mb1234
    inline_response_401:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    SendMailAdv_from:
      required:
      - email
      type: object
      properties:
        email:
          type: string
          description: The email address
          example: business@company.com
        name:
          type: string
          description: (optional) Name to use for the sending contact.
          example: The Man
      description: The information to use for the From address in the email. from.
    SendMailAdv_to:
      required:
      - email
      type: object
      properties:
        email:
          type: string
          description: The email address
          example: johndoe@isp.com
        name:
          type: string
          description: (optional) Name to use for the destination contact.
          example: John Doe
      description: An Email Contact
    SendMailAdv_replyto:
      required:
      - email
      type: object
      properties:
        email:
          type: string
          description: The email address
          example: support@company.com
        name:
          type: string
          description: (optional) Name to use for the sending contact.
          example: Support Staff
      description: An Email Contact
    SendMailAdv_cc:
      required:
      - email
      type: object
      properties:
        email:
          type: string
          description: The email address
          example: janedoe@isp.com
        name:
          type: string
          description: (optional) Name to use for the CC contact.
          example: Jane Doe
      description: An Email Contact
    SendMailAdv_bcc:
      required:
      - email
      type: object
      properties:
        email:
          type: string
          description: The email address
          example: records@company.com
        name:
          type: string
          description: (optional) Name to use for the BCC contact.
          example: Records Department
      description: An Email Contact
    SendMailAdv_attachments:
      required:
      - data
      type: object
      properties:
        filename:
          type: string
          description: (optional) Filename to specify for the attachment.
          example: company_logo.png
        data:
          type: string
          description: Contents of the attached file (must be base64 encoded)
          format: binary
      description: A File attachment for an email
  responses:
    BadInput:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_401'
    AlreadyExists:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            required:
            - code
            - message
            type: object
            properties:
              code:
                type: string
              message:
                type: string
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_401'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_401'
  parameters:
    offsetParam:
      name: offset
      in: query
      description: Number of items to skip before returning the results.
      required: false
      style: form
      explode: true
      schema:
        minimum: 0
        type: integer
        format: int32
        default: 0
    limitParam:
      name: limit
      in: query
      description: Maximum number of items to return.
      required: false
      style: form
      explode: true
      schema:
        maximum: 100
        minimum: 1
        type: integer
        format: int32
        default: 20
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: X-API-KEY
      in: header
  links: {}
  callbacks: {}
